---
title: "TERGM"
output: html_document
params: 
  element: "Al2O3"
---


```{r}
#install.packages(c("network", "btergm", "tergm", "ggraph", "intergraph"))
```


```{r}
#install.packages(c("ggraph", "intergraph"))
```

```{r}
library(network)
library(tergm)
library(sna)
library(igraph)
library(ggraph)
library(intergraph)
library(ndtv)
```

```{r}
element   <- params$element
ele_f_t15 <- paste0("data/", element, "_edge_list_data_2015.csv")
ele_f_t20 <- paste0("data/", element, "_edge_list_data_2020.csv")

edges_t15 <- read.csv(ele_f_t15)
edges_t20 <- read.csv(ele_f_t20)
```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
#head(edges_t1)
dim(edges_t15)  
```

```{r}
nodes <- unique(c(edges_t15$from, edges_t15$to, edges_t20$from, edges_t20$to))
node_df <- data.frame(name = nodes)
```

```{r}
length(nodes)
```

```{r}
net1 <- network(edges_t15, 
                directed = TRUE, vertices = node_df, matrix.type = "edgelist")
net2 <- network(edges_t20, directed = TRUE, vertices = node_df, matrix.type = "edgelist")

indeg1 <- sna::degree(net1, cmode="indegree")
indeg2 <- sna::degree(net2, cmode="indegree")

network::set.edge.attribute(net1, "weight", edges_t15$weight)
network::set.edge.attribute(net2, "weight", edges_t20$weight)

network::set.vertex.attribute(net1, "indegree", indeg1)
network::set.vertex.attribute(net2, "indegree", indeg2)
```

```{r}
net.list <- list(net1, net2)
```


```{r}
# === 6. (선택) 예시 공변량 생성 ===
# 두 시점마다 동일 크기의 행렬 리스트로 생성해야 함
set.seed(123)
X1 <- matrix(runif(length(nodes)^2, 0, 1), nrow = length(nodes))
X2 <- matrix(runif(length(nodes)^2, 0, 1), nrow = length(nodes))
X.list <- list(X1, X2)

# === 7. TERGM (btergm) 모델 추정 ===
set.seed(100)
model <- tergm(net.list ~ edges 
                #+ gwesp(0.1, fixed = TRUE) 
                #+ edgecov(X.list)
                + mutual
                + nodecov("indegree")
                + diff(attr="indegree", dir="t-h")
                , 
                estimate="CMLE", times=0:2)

# === 8. 결과 확인 ===
r_f_name <- paste0("result/", element, "_models.txt")  # => "network_plot_2050.png"
sink(r_f_name, append = TRUE)
summary(model)
sink()
```

```{r}
# nsim = 생성할 네트워크 수 (기본값은 1)
sim <- simulate(model, nsim = 1, time.slices = 5, nw.start="first")

# === 2. 결과 확인 ===
# sim은 네트워크 객체 형태의 리스트로 반환됩니다.
class(sim)       # "list"
length(sim)      # 예: 1
class(sim[[1]])  # "network"
```

```{r}
str(sim, max.level = 1)
```

```{r}
plot.par = list(edge.col="darkgray",
displaylabels = T,
label.cex=.8,
label.col="blue",
vertex.cex = 1)

h_f_path <- paste0("html/", element, "_simulation_movie.html") 
render.d3movie(sim, htmlfile = "simulation_movie.html")
```


```{r}
filename <- paste0("img/", element, "_network_plot_2015.png")  # => "network_plot_2050.png"
png(filename, width = 1200, height = 900, res = 150)

sim <- simulate(model, nsim = 1, time.slices = 3, nw.start="last")
deg <- sna::degree(net1, gmode = "digraph", cmode="indegree")
label <- ifelse(deg>=2, network.vertex.names(net1), "")
set.seed(150)
plot.network(net1,
             label=label,
             vertex.cex = sqrt(deg+1)*0.8,
             displaylabels = TRUE,
             vertex.col = "skyblue",
             vertex.border=0.3,
             edge.col = "grey60",
             label.cex = 0.6,
             edge.lwd = 0.1,
             main = "TPU Network : 2015 ~",
             displayisolates=FALSE,
             mode="fruchtermanreingold")
dev.off()
```



```{r}

filename <- paste0("img/", element, "_network_plot_2020.png")  # => "network_plot_2050.png"
png(filename, width = 1200, height = 900, res = 150)

deg <- sna::degree(net2, gmode = "digraph", cmode="indegree")
label <- ifelse(deg>=2, network.vertex.names(net2), "")
set.seed(513)
plot.network(net2,
             label=label,
             vertex.cex = sqrt(deg+1)*0.8,
             displaylabels = TRUE,
             vertex.col = "skyblue",
             vertex.border=0.3,
             edge.col = "grey60",
             label.cex = 0.6,
             edge.lwd = 0.1,
             main = "TPU Network : 2020 ~",
             displayisolates=FALSE,
             mode="fruchtermanreingold")
dev.off()
```



```{r}
# Simulated results
filename <- paste0("img/", element, "_network_plot_2025.png")  # => "network_plot_2050.png"
png(filename, width = 1200, height = 900, res = 150)

simp1 <- network.extract(sim, at=1)
deg <- sna::degree(simp1, gmode = "digraph", cmode="indegree")
label <- ifelse(deg>=2, network.vertex.names(simp1), "")
set.seed(52113)
plot.network(simp1,
             label=label,
             vertex.cex = sqrt(deg+1)*0.8,
             displaylabels = TRUE,
             vertex.col = "skyblue",
             vertex.border=0.3,
             edge.col = "grey60",
             label.cex = 0.6,
             edge.lwd = 0.3,
             main = "TPU Network : 2025 ~",
             displayisolates=FALSE,
             mode="fruchtermanreingold"
             )
dev.off()
```

```{r}
# Simulated results

filename <- paste0("img/", element, "_network_plot_2030.png")  # => "network_plot_2050.png"
png(filename, width = 1200, height = 900, res = 150)

simp2 <- network.extract(sim, at=2)
deg <- sna::degree(simp2, gmode = "digraph", cmode="indegree")
label <- ifelse(deg>=3, network.vertex.names(simp2), "")
set.seed(5156)
plot.network(simp2,
             label=label,
             vertex.cex = sqrt(deg+1)*0.8,
             displaylabels = TRUE,
             vertex.col = "skyblue",
             vertex.border=0.3,
             edge.col = "grey60",
              label.cex = 0.6,
              edge.lwd = 0.3,
             main = "TPU Network : 2030 ~",
             displayisolates=FALSE,
             mode="fruchtermanreingold")
dev.off()
```


```{r}
# Simulated results
simp3 <- network.extract(sim, at=3)
deg <- sna::degree(simp3, gmode = "digraph", cmode="indegree")
label <- ifelse(deg>=2, network.vertex.names(simp3), "")
set.seed(515)

# 1️⃣ 저장할 파일 열기
filename <- paste0("img/", element, "_network_plot_2035.png")  # => "network_plot_2050.png"

png(filename, width = 1200, height = 900, res = 150)
plot.network(simp3,
             label=label,
             vertex.cex = sqrt(deg+1)*0.8,
             displaylabels = TRUE,
             vertex.col = "skyblue",
             vertex.border=0.3,
             edge.col = "grey60",
             label.cex = 0.6,
             edge.lwd = 0.1,
             main = "TPU Network : 2035 ~",
             displayisolates=FALSE,
             mode="fruchtermanreingold")
dev.off()

```



